In [1]:
#打开文件，查看内容并读取
import pandas as pd
import numpy as np

data = pd.read_csv("D:/intro/DaSE_intro/10.18/stuGrade.csv",usecols=["chinese", "math", "english"]) #usecols:读取第几列
data = np.array(data)
print(data)

[[74 87 82]
 [92 88 90]
 [87 82 81]
 [98 97 96]
 [62 51 60]]


In [2]:
#计算各科平均成绩
average = []
for i in range(3):
    sum = 0
    for j in range(5):
        sum += data[j][i]
    sum /= 5
    average.append(sum)
for i in range(3):
    print("%.2f" %average[i]) #输出两位小数

82.60
81.00
81.80


In [3]:
import time

s1 = '10215501415 YifeiLong'+'\n'
s2 = '82.60' + ','+'81.00'+','+'81.80'+'\n'
s3 = time.strftime("%Y-%m-%d %H:%M:%S",time.localtime()) +'\n'
time.sleep(2) #停2秒再运行
s4 = time.strftime("%Y-%m-%d %H:%M:%S",time.localtime())

with open('D:/intro/DaSE_intro/10.18/my.txt','w') as f2: #自动关闭文件
    f2.write(s1)
    f2.write(s2)
    f2.write(s3)
    f2.write(s4)